---
- hosts: all
  become: true
  
  vars:
    clusters:
      - name: auh
        kubecontext: "auh"
        kubeconfig: "{{ ansible_env.HOME }}/.kube/auh.kubeconfig"
        node_labels:
          topology.kubernetes.io/region: "auh"
          topology.kubernetes.io/zone: "auh-zone"
        argocd_nodeport: 32000
        istio_igw_http_port: 31000
        istio_igw_https_port: 31001
        api_server_port: 6443

      # - name: dxb
      #   kubecontext: "dxb"
      #   network: "dxb-net"
      #   kubeconfig: "{{ ansible_env.HOME }}/.kube/dxb.kubeconfig"
      #   node_labels:
      #     topology.kubernetes.io/region: "dxb"
      #     topology.kubernetes.io/zone: "dxb-zone"
      #   argocd_nodeport: 32002
      #   istio_igw_http_port: 31002
      #   istio_igw_https_port: 31003
      #   api_server_port: 6443

  tasks:

    - name: Install kubectl 
      include_tasks: tasks/kubectl.yml 

    - name: Install k3s 
      include_tasks: tasks/k3s.yml    

    - name: Install helm 
      include_tasks: tasks/helm.yml   

    - name: Install cilium 
      include_tasks: tasks/install_cilium.yml                        

    # - name: Configure ArgoCD for all clusters
    #   include_tasks: tasks/install_argo.yml
    #   loop: "{{ clusters }}"
    #   loop_control:
    #     loop_var: cluster 
