Vagrant.configure("2") do |config|
  config.vm.box = "ubuntu/bionic64"

  config.vm.provider "virtualbox" do |vb|
    vb.memory = "4096"
    vb.cpus = 3
  end

  # First K3s cluster (VM1)
  config.vm.define "auh" do |auh|
    auh.vm.hostname = "auh"
    auh.vm.network "private_network", ip: "10.0.0.101"
    auh.vm.network "forwarded_port", guest: 6443, host: 7443
    auh.vm.provision "ansible_local" do |ansible|
      ansible.playbook = "main.yml"
      ansible.extra_vars = { 
        "inventory_hostname" => "auh",
        "pod_cidr" => "10.1.0.0/16",  
        "service_cidr" => "10.3.0.0/16",  
        "k3s_api_host_ip" => "10.0.0.101"
      }
    end
  end

  # # Second K3s cluster (VM2)
  # config.vm.define "dxb" do |dxb|
  #   dxb.vm.hostname = "dxb"
  #   dxb.vm.network "private_network", ip: "10.0.0.102"
  #   dxb.vm.network "forwarded_port", guest: 6443, host: 7444
  #   dxb.vm.provision "ansible_local" do |ansible|
  #     ansible.playbook = "main.yml"
  #     ansible.extra_vars = { 
  #       "inventory_hostname" => "dxb",
  #       "pod_cidr" => "10.2.0.0/16", 
  #       "service_cidr" => "10.4.0.0/16", 
  #       "k3s_api_host_ip" => "10.0.0.102"
  #     }
  #   end
  # end


end
