---
- name: Set variables
  set_fact:
    cilium_namespace: "cilium"

- name: Check if Cilium namespace exists
  command: kubectl get namespace {{ cilium_namespace }}
  register: cilium_namespace_check
  failed_when: false
  changed_when: false

# Step 2: Create the namespace if not exists
- name: Create Cilium namespace
  command: kubectl create namespace {{ cilium_namespace }}
  when: cilium_namespace_check.rc != 0

# Step 3: Check if Cilium is installed
- name: Check if Cilium is installed
  shell: helm list -n {{ cilium_namespace }} | grep cilium
  register: cilium_check
  failed_when: false
  changed_when: false

# Step 4: Install Cilium if not installed
- name: Install Cilium
  shell: |
    helm repo add cilium https://helm.cilium.io/
    helm repo update
    helm install cilium cilium/cilium --version 1.15.11 \
      --namespace {{ cilium_namespace }} \
      --set operator.replicas=1
  when: cilium_check.rc != 0
